configfile : "config/config.yaml"
import pandas as pd

samples = pd.read_csv(config["samples"],index_col="sample", sep ='\t')
IDS=[s for s in list(samples.index)]
all_fq = [ID + "_1" for ID in IDS] + [ID + "_2" for ID in IDS]
wildcard_constraints:
    sample= "[^/]+",

include: "rules/bowtie.smk"
include: "rules/samtools.smk"
include: "rules/qc.smk"
include: "rules/msa.smk"
include: "rules/denovo.smk"
include: "rules/artificialref.smk"
include: "rules/screen.smk"
include: "rules/decontamination.smk"

rule all:
    input:
        assembled_samples = expand("results/fasta/{sample}.fa",sample=IDS),
        multiqc_reports = "results/qc/multiqc_report.html",










