samples: "samples.tsv"

# parameters:
references: "reference.fa"

bowtie2:
  local: "--local" #"--local" or " "
  ma: "0" #scores can be configured with the --ma (match bonus)

multiqcparam: "-f"

trimmomatic:
  trailing: "20"

tree:
  method: "iqtree" #{fasttree,raxml,iqtree}

consenus:
  q: 20 #Minimum quality score threshold to count base

variability:
  l: 2 #Window length

skip_trimming: 'False'
skip_fastQC: 'False'
skip_qualimap: 'False'
