ref: "reference/NC_045512.2"
samples: "samples.tsv"
#parameters:
bowtie2:
  local: "--local" #"--local" or " "
  ma: "0" #scores can be configured with the --ma (match bonus)
multiqcparam: "-f"
tree:
  method: "iqtree" #{fasttree,raxml,iqtree}
consenus:
  q: 20 #Minimum quality score threshold to count base
skip_trimming: 'False'
skip_fastQC: 'False'
skip_qualimap: 'False'